# Generated by Django 3.1.1 on 2021-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='category',
            field=models.CharField(choices=[('wears', 'wears'), ('watch', 'watch'), ('Electronics', 'Electronics'), ('Shoes', 'Shoes')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='product_table',
            name='display_type',
            field=models.CharField(choices=[('Featured product', 'Featured product'), ('Category product', 'Category product'), ('None', 'None')], default=None, max_length=20),
        ),
    ]
