# Generated by Django 3.1.1 on 2021-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20210928_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
