# Generated by Django 3.1.1 on 2021-10-25 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=11)),
                ('purchased', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_table',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_cashout', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.CharField(max_length=11)),
                ('cashout', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
